name: Deploy Static Website

on:
  push:
    branches:
      - leaderboard
    paths:
      - 'docs/**'
      - '!docs/leaderboard/results/**'
      - '!docs/leaderboard/processed/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch results branch
        run: |
          git fetch origin results:results

      - name: Copy processed results from results branch
        run: |
          mkdir -p docs/leaderboard/processed
          git checkout results -- docs/leaderboard/processed || echo "No processed results found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true