name: Build and Deploy Leaderboard

on:
  push:
    branches:
      - main
    paths:
      - 'leaderboard/**'
      - '!leaderboard/results/**'
      - '!leaderboard/processed/**'
  repository_dispatch:
    types: [trigger-deploy-leaderboard]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Fetch the results branch for processed data
      - name: Fetch results branch
        run: |
          git fetch origin results:results

      - name: Copy processed results from results branch
        run: |
          mkdir -p leaderboard/processed
          git checkout results -- leaderboard/processed || echo "No processed results found"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./leaderboard
        run: npm install

      - name: Build
        working-directory: ./leaderboard
        run: npm run build

      - name: Create docs directory if it doesn't exist
        run: mkdir -p docs

      - name: Copy build to docs/leaderboard
        run: |
          mkdir -p docs/leaderboard
          cp -r leaderboard/build/* docs/leaderboard/
          mkdir -p docs/leaderboard/processed
          cp -r leaderboard/processed/* docs/leaderboard/processed/ || true
      
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/leaderboard
          git commit -m "Update leaderboard" || echo "No changes to commit"
          git push