name: Process Leaderboard Results

on:
  pull_request:
    paths:
      - 'docs/leaderboard/results/**'
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'docs/leaderboard/results/**'

jobs:
  process-results:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Process results
        run: |
          mkdir -p docs/leaderboard/processed
          node .github/scripts/process-results.js

      - name: Create PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read the processed results to get the new submission
            const processedPath = 'docs/leaderboard/processed/combined-results.json';
            let combinedResults = [];
            
            if (fs.existsSync(processedPath)) {
              const data = fs.readFileSync(processedPath, 'utf8');
              combinedResults = JSON.parse(data);
            }
            
            // Find the new submission (last one in the array)
            const newSubmission = combinedResults[combinedResults.length - 1];
            
            if (newSubmission) {
              const comment = `## Leaderboard Submission Processed ✅
              
              **Model**: ${newSubmission.model}
              **Production Score**: ${newSubmission.productionScore}
              **Milestones**: ${newSubmission.milestones}
              **Lab Tasks Success Rate**: ${newSubmission.labTasksSuccessRate}%
              **Most Complex Item**: ${newSubmission.mostComplexItem}
              **Status**: Pending verification
              
              Your submission has been processed and will be marked as "Verified" once this PR is merged.
              
              ---
              *This is an automated message from the FLE leaderboard system.*`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }

      - name: Save processed results
        run: |
          # Save the processed results temporarily
          mkdir -p /tmp/processed
          cp -r docs/leaderboard/processed/* /tmp/processed/ || true

      - name: Fetch and checkout results branch
        run: |
          # Discard any local changes
          git reset --hard HEAD
          
          # Fetch the results branch or create it if it doesn't exist
          git fetch origin results || true
          git checkout results 2>/dev/null || git checkout -b results
          
          # If the branch exists remotely, reset to its state
          git fetch origin results && git reset --hard origin/results || true

      - name: Copy processed results back
        run: |
          # Copy the processed results back
          mkdir -p docs/leaderboard/processed
          cp -r /tmp/processed/* docs/leaderboard/processed/ || true

      - name: Commit and push to results branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/leaderboard/processed
          git commit -m "Update processed leaderboard results" || echo "No changes to commit"
          git push -f origin results

      # Trigger the deploy workflow
      - name: Trigger deploy workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy-leaderboard