name: Process Leaderboard Results

on:
  pull_request:
    paths:
      - 'leaderboard/results/**'
  push:
    branches:
      - main
    paths:
      - 'leaderboard/results/**'

jobs:
  process-results:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Process results
        run: |
          mkdir -p leaderboard/processed
          node .github/scripts/process-results.js

      - name: Save processed results
        run: |
          # Save the processed results temporarily
          mkdir -p /tmp/processed
          cp -r leaderboard/processed/* /tmp/processed/ || true

      - name: Fetch and checkout results branch
        run: |
          # Discard any local changes
          git reset --hard HEAD
          
          # Fetch the results branch or create it if it doesn't exist
          git fetch origin results || true
          git checkout results 2>/dev/null || git checkout -b results
          
          # If the branch exists remotely, reset to its state
          git fetch origin results && git reset --hard origin/results || true

      - name: Copy processed results back
        run: |
          # Copy the processed results back
          mkdir -p leaderboard/processed
          cp -r /tmp/processed/* leaderboard/processed/ || true

      - name: Commit and push to results branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add leaderboard/processed
          git commit -m "Update processed leaderboard results" || echo "No changes to commit"
          git push -f origin results

      # Trigger the deploy workflow
      - name: Trigger deploy workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy-leaderboard