name: Process Leaderboard Results

on:
  pull_request:
    paths:
      - 'leaderboard/results/**'
  push:
    branches:
      - main
    paths:
      - 'leaderboard/results/**'

jobs:
  process-results:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create processed directory
        run: mkdir -p leaderboard/processed

      - name: Process results
        run: |
          node .github/scripts/process-results.js

      - name: Fetch and checkout results branch
        run: |
          git fetch origin results:results || git checkout -b results
          git checkout results
          git pull origin results || true

      - name: Copy processed results
        run: |
          mkdir -p leaderboard/processed
          cp -r leaderboard/processed/* leaderboard/processed/ || true

      - name: Commit and push to results branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add leaderboard/processed
          git commit -m "Update processed leaderboard results" || echo "No changes to commit"
          git push origin results

      # Trigger the deploy workflow
      - name: Trigger deploy workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy-leaderboard