name: "Publish to TestPyPI"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run:
    name: "Build and publish to TestPyPI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install 3.12

      - name: Build
        run: uv build

      - name: Publish to TestPyPI
        run: uv publish --trusted-publishing always --index testpypi